### ISSUE TITLE
Add a warning when deleting a label

### ISSUE THREAD

**Issue by bourdakos1** [cloud-annotations/cloud-annotations-client#6]
When deleting a label all images in that label will become unlabeled.
This is more important in localization, because they will also lose their bounding boxes.

**Comment by moficodes** [comment]
I just tested and deleted a label that had images and got no warning.

Might need to revisit this.

**Comment by bourdakos1** [comment]
I just keep all issues on github.com/cloud-annotations/training

reopen this there
